language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4.2"
  - "5.3"
  
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

script:
  - npm test
